mysql:
  host: 192.168.1.109
  port: 3306
  url: jdbc:mysql://192.168.1.109:3306/stock?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
  username: root
  password: 123456
  driver: com.mysql.cj.jdbc.Driver
  database: stock